### PR TITLE
Update aws-iot-fleetwise-edge recipe to v0.1.4

### PR DESCRIPTION
**Pull request by olgaakulinushkina**
_Description of changes:_

Updates aws-iot-fleetwise-edge recipe to the latest released version v0.1.4 of aws-iot-fleetwise-edge.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by thomas-roos** [comment]
Hi,
please submit your pull request to gatesgarth-next (see [contribution guideline:](https://github.com/aws4embeddedlinux/meta-aws/blob/master/CONTRIBUTING.md))
Also like to ask if there are any plans to upstream this recipe to master, so that customers using kirkstone and dunfell can also use it? Thank you!

Cheers, 
Thomas

**Comment by olgaakulinushkina** [comment]
Hi,
thank you! We would like to upstream it to master at some point but it requires some time for testing on our side that wasn't done yet.

Thanks,
Olga

**Comment by thomas-roos** [comment]
ERROR: Nothing PROVIDES 'aws-sdk-cpp' (but /tmp/layers/meta-aws/recipes-iot/aws-iot-fleetwise/aws-iot-fleetwise-edge.bb DEPENDS on or otherwise requires it). Close matches: aws-crt-cpp
did you build it locally?

**Review by nateglims — APPROVED** [review]

**Pull request merged**
