### PR TITLE
updates on recipes-sdk

### PR DESCRIPTION
**Pull request by thomas-roos**

### CODE REVIEW

**Comment by nateglims** [comment]
Is this update dropping the 'common' requirement from the CRT recipes or am I missing something? If so that's excellent.

**Comment by thomas-roos** [comment]
Yes😊

**Review by nateglims — APPROVED** [review]
I'm not sure if we should ship with the `-W` flags suppressed or not, but I will defer to your judgement.

**Comment by thomas-roos** [comment]
I think it's ok for now, but for the future we should aim for warn=error in all software products in this layer. There are more such things in patches...

**Pull request merged**
