### PR TITLE
Fix packaging with multilib and cleanup the recipes a bit

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by shr-project** [comment]
FWIW: I didn't change packaging of aws-c-sdkutils but I guess the cmake files should go to PN-dev as in other recipes, see:

```
martin@jama /OE/build/oe-core $ find tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib/aws-c-sdkutils
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib/aws-c-sdkutils/cmake
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib/aws-c-sdkutils/cmake/shared
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib/aws-c-sdkutils/cmake/shared/aws-c-sdkutils-targets-release.cmake
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib/aws-c-sdkutils/cmake/shared/aws-c-sdkutils-targets.cmake
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib/aws-c-sdkutils/cmake/aws-c-sdkutils-config.cmake
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils/usr/lib/libaws-c-sdkutils.so.1.0.0
martin@jama /OE/build/oe-core $ find tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/lib
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/lib/libaws-c-sdkutils.so
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws/sdkutils
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws/sdkutils/endpoints_rule_engine.h
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws/sdkutils/exports.h
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws/sdkutils/partitions.h
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws/sdkutils/resource_name.h
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws/sdkutils/sdkutils.h
tmp-glibc/work/core2-64-oe-linux/aws-c-sdkutils/0.1.5-r0/packages-split/aws-c-sdkutils-dev/usr/include/aws/sdkutils/aws_profile.h
```

**Comment by thomas-roos** [comment]
Hi,
thank you a lot for the contribution - I did review your changes - all perfect, but could you please create your pull request against master-next?
Thank you!

**Comment by thomas-roos** [comment]
see here: https://github.com/aws4embeddedlinux/meta-aws/blob/master/CONTRIBUTING.md?plain=1#L34

**Review by thomas-roos — APPROVED** [review]

**Pull request merged**
