### PR TITLE
Revert setuptools patch

### PR DESCRIPTION
**Pull request by rarengifoArthrex**
reverting previous patch to fix setuptools3 that has now been addressed. This was causing issues when it came to fetching the correct version of library.  In my particular case it would take aws-iot-device-sdk-python-v2_1.5.4 instead of aws-iot-device-sdk-python-v2_1.7.0

this will need to be merged into kirkstone as well

### CODE REVIEW

**Comment by thomas-roos** [comment]
thank you for the suggested changes!
Please do pull requests to the *-next branches only. [please read this](https://github.com/aws4embeddedlinux/meta-aws/blob/master/CONTRIBUTING.md)
I tried to understand the history of the setuptools3.bbclass issue. [here](https://git.yoctoproject.org/poky/log/meta/classes/setuptools3.bbclass)
I applied your suggested changes manually, but beginning with reverting [[aws-iot-device-sdk-python-v1_git](https://github.com/aws4embeddedlinux/meta-aws/pull/332/commits/6cf7ea6a597b48ccbd4779de55143326e1e36ee8#diff-09a6ca0ffd2af2cdb0e6846ab1d88bdb5e3eaff161052dd23f2165cd1c6b2d2c)](https://github.com/aws4embeddedlinux/meta-aws/pull/332/commits/6cf7ea6a597b48ccbd4779de55143326e1e36ee8) I was getting errors.
I think the correct solution for now is to `inherit setuptools3_legacy` as descriped [here](https://git.yoctoproject.org/poky/commit/meta/classes/setuptools3_legacy.bbclass?id=47905882113e2905a8fc9664c5ab338e038c533b) - but as suggested in the long term the distutils installers should be replaced.

**Comment by rarengifoArthrex** [comment]
HI @thomas-roos thanks for the feedback.  I can go ahead and make the correct pr into master-next and kirkstone-next if you want. 

Regarding the error, yes i saw it originally which is why one of the reverts left part of the code in which was needed to avoid that. https://github.com/aws4embeddedlinux/meta-aws/pull/332/commits/6cf7ea6a597b48ccbd4779de55143326e1e36ee8

**Comment by thomas-roos** [comment]
Thank you for that information - I think I will watch that presentation next week and then think of what's best. Also have colleague reviewing my PR. But as I don't know what the different packages using in my understanding setuptools3_legacy.bbclass is save for now, but as you said will be removed with python 3.12.

**Comment by thomas-roos** [comment]
Hi @rarengifoArthrex @kk6ho,
did see the talk on the yps2022.5 - so in my understanding we should now check which projects still uses `distutils`. I did this:
git://github.com/boto/boto3.git
-> ok
git://github.com/boto/botocore.git
-> ok
git://github.com/boto/s3transfer.git
-> ok
git://github.com/sankalpjonn/timeloop.git
-> ok
gitsm://github.com/awslabs/aws-crt-python.git
-> distutils
aws-iot-device-sdk-python-v1
-> https://github.com/aws/aws-iot-device-sdk-python.git
-> distutils
-> there is already pull request on replacing distutils by setuptools
git://github.com/aws/aws-iot-device-sdk-python-v2.git
-> ok
git://github.com/aws/aws-greengrass-core-sdk-python.git
-> ok
git://github.com/aws/aws-cli.git
-> ok

And only for  `aws-iot-device-sdk-python-v1_1.5.2.bb` and `aws-crt-python_0.13.11.bb` use `setuptools-legacy`
Would you like to do this and create a new PR against master-next with that modifications?

**Comment by rarengifoArthrex** [comment]
@thomas-roos thanks for looking into this.  I should have some time next week to do this and will create those prs. 

if the same changes need to go into kirkstone, should i put a separate pr out into kirstone-next?

**Comment by thomas-roos** [comment]
that sounds great - please if possible do both. master-next and kirkstone-next

**Pull request closed without merging**
