### PR TITLE
 removed pv variable as it was causing the wrong recipes to be used

### PR DESCRIPTION
**Pull request by rarengifoArthrex**
Signed-off-by: Rengifo, Rodrigo <rodrigo.rengifo@artrhex.com>

### CODE REVIEW

**Comment by nateglims** [comment]
There is an error in our kirkstone layer-check setup so please ignore this check failure.

**Review by nateglims — APPROVED** [review]

**Comment by thomas-roos** [comment]
Thank you for this - could you provide a PR against master-next as well?

**Comment by rarengifoArthrex** [comment]
@thomas-roos yes i'm looking at that next.  had to wait for my master build to run overnight so i could confirm any changes i made prior to sending pr.  Will have something out in the next couple of hours.

**Comment by rarengifoArthrex** [comment]
@thomas-roos actually i was looking at it and the recipes i updated here no longer exist in master branch.  should master hold all the older recipes in case people want to use older versions of aws? 

on a side note, how often does a -next branch get merged into a main line branch?

**Comment by rarengifoArthrex** [comment]
ok so in that case there is probably no need for me to do a pr against master.

as for the use case we currently run on particular aws versions (iot v2 1.7 and crt python 12.1). it's probably ok for it to be revved on master, we just need to make the appropriate changes on our end and hopefully, it won't affect compatibility.

**Comment by thomas-roos** [comment]
Hi, I was thinking of this: https://github.com/aws4embeddedlinux/meta-aws/commit/faa36b331cdf2c35c97fa18d70afb577d4fc800f
But all good, thank you for your contribution!

**Pull request merged**
